Presentation Layers/Yumiki.Web.Master/Areas/WellCovered/Controllers/LiveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yumiki.Business.WellCovered.Interfaces;
using Yumiki.Commons.Dictionaries;
using Yumiki.Commons.Exceptions;
using Yumiki.Commons.Settings;
using Yumiki.Entity.MoneyTrace.ServiceObjects;
using Yumiki.Entity.WellCovered;
using Yumiki.Web.Base;
using Yumiki.Web.WellCovered.Models;

namespace Yumiki.Web.WellCovered.Controllers
{
    public class LiveController : BaseController<ILiveService>
    {
        public const string ObjectID = "objectID";
        public const string RecordID = "recordID";
        public const string RequestVerificationToken = "__RequestVerificationToken";

        public ActionResult List(string objectID, bool active)
        {
            MD_Live live = new MD_Live();

            try
            {
                live = BusinessService.FetchViewObjectData(objectID, active);
            }
            catch (Exception ex)
            {
                SendError(ex);
            }

            return View(live);
        }

        public ActionResult Search(string keywords, int? pageIndex)
        {
            if (string.IsNullOrWhiteSpace(keywords))
            {
                return View();
            }

            if (!pageIndex.HasValue)
            {
                pageIndex = 1;
            }

            GetSearchIndexResponse response = new GetSearchIndexResponse();
            try
            {
                GetSearchIndexRequest request = new GetSearchIndexRequest()
                {
                    Keywords = keywords,
                    UserID = CurrentUser.UserID,
                    CurrentPage = pageIndex.Value
                };

                response = BusinessService.Search(request);
            }
            catch (Exception ex)
            {
                SendError(ex);
            }

            return View(response);
        }

        // GET: App/Create
        public ActionResult Create(string objectID)
        {
            MD_LiveRecord liveRecord = new MD_LiveRecord();
            try
            {
                liveRecord.Fields = BusinessService.GetFields(objectID).Select(c => new MD_Field(c));

                MD_Field isActiveField = liveRecord.Fields.Where(c => c.ApiName.Equals(CommonProperties.IsActive, StringComparison.InvariantCultureIgnoreCase)).FirstOrDefault();
                if(isActiveField != null)
                {
                    isActiveField.Value = true;
                }

                InitDataSource(liveRecord.Fields);
            }
            catch (Exception ex)
            {
                SendError(ex);
            }

            liveRecord.ObjectID = objectID;

            return View(liveRecord);
        }

        // POST: App/Create
        [HttpPost]
        public ActionResult Create(FormCollection formCollection)
        {
            string objectID = formCollection[LiveController.ObjectID];
            try
            {
                Dictionary<string, string> dicFields = new Dictionary<string, string>();

                foreach (string key in formCollection.AllKeys)
                {
                    if (!key.Equals(LiveController.RequestVerificationToken, StringComparison.InvariantCultureIgnoreCase))
                    {
                        dicFields.Add(key, formCollection[key]);
                    }
                }

                BusinessService.Add(objectID, dicFields);

                return RedirectToAction("List", new { active = true, objectID = objectID });
            }
            catch (Exception ex)
            {
                SendError(ex);
            }

            MD_LiveRecord liveRecord = new MD_LiveRecord();

            liveRecord.ObjectID = objectID;

            liveRecord.Fields = SetFieldValues(formCollection);
            InitDataSource(liveRecord.Fields);

            return View(liveRecord);
        }

        // GET: App/Edit
        public ActionResult Edit(string objectID, string recordID)
        {
            MD_LiveRecord liveRecord = new MD_LiveRecord();

            try
            {
                liveRecord.ObjectID = objectID;
                liveRecord.LiveRecordID = recordID;

                liveRecord.Fields = BusinessService.GetFieldsByID(objectID, recordID).Select(c => new MD_Field(c));
                InitDataSource(liveRecord.Fields);

                //Get all attachments from object
                liveRecord.Attachments = BusinessService.GetAttachments(recordID).Select(c => new MD_Attachment(c));
            }
            catch (Exception ex)
            {
                SendError(ex);
            }

            return View(liveRecord);
        }

        // POST: App/Edit
        [HttpPost]
        public ActionResult Edit(FormCollection formCollection)
        {
            string objectID = formCollection[LiveController.ObjectID];
            string recordID = formCollection[LiveController.RecordID];

            try
            {
                Dictionary<string, string> dicFields = new Dictionary<string, string>();

                foreach (string key in formCollection.AllKeys)
                {
                    if (!key.Equals(LiveController.RequestVerificationToken, StringComparison.InvariantCultureIgnoreCase))
                    {
                        dicFields.Add(key, formCollection[key]);
                    }
                }

                BusinessService.Update(objectID, recordID, dicFields);

                return RedirectToAction("List", new { active = true, objectID = objectID });
            }
            catch (Exception ex)
            {
                SendError(ex);
            }

            MD_LiveRecord liveRecord = new MD_LiveRecord();

            liveRecord.ObjectID = objectID;
            liveRecord.LiveRecordID = recordID;

            liveRecord.Fields = SetFieldValues(formCollection);
            InitDataSource(liveRecord.Fields);

            //Get all attachments from object
            liveRecord.Attachments = BusinessService.GetAttachments(recordID).Select(c => new MD_Attachment(c));

            return View(liveRecord);
        }

        /// <summary>
        /// When validation fails, add values which entered by user back to UI by assign value in submitted form to return Field list.
        /// </summary>
        /// <param name="formCollection">Form Collection which contains entered values.</param>
        /// <returns></returns>
        private IEnumerable<MD_Field> SetFieldValues(FormCollection formCollection)
        {
            IEnumerable<MD_Field> fields = new List<MD_Field>();
            try
            {
                fields = BusinessService.GetFields(formCollection[LiveController.ObjectID]).Select(c => new MD_Field(c));

                foreach (string key in formCollection.AllKeys)
                {
                    MD_Field selectedField = fields.Where(c => c.ApiName == key).FirstOrDefault();

                    if (selectedField != null)
                    {
                        string value = formCollection[key];

                        if (!string.IsNullOrWhiteSpace(value))
                        {
                            switch (selectedField.FieldType)
                            {
                                case EN_DataType.E_INT:
                                    selectedField.Value = int.Parse(value);
                                    break;
                                case EN_DataType.E_DECIMAL:
                                    selectedField.Value = decimal.Parse(value);
                                    break;
                                case EN_DataType.E_BOOL:
                                    selectedField.Value = bool.Parse(value.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)[0]);
                                    break;
                                case EN_DataType.E_DATE:
                                    selectedField.Value = DateTime.Parse(value).Date;
                                    break;
                                case EN_DataType.E_DATETIME:
                                    selectedField.Value = DateTime.Parse(value);
                                    break;
                                case EN_DataType.E_TIME:
                                    selectedField.Value = DateTime.Parse(value).TimeOfDay;
                                    break;
                                default:
                                    //Datasource Type and String type use String as it is.
                                    selectedField.Value = value;
                                    break;
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                SendError(ex);
            }

            return fields;
        }

        // POST:
        [HttpPost]
        public ActionResult PublishApp(string appID)
        {
            try
            {
                BusinessService.PublishApp(appID);

                SendInformation("Publish App Successfully!");
            }
            catch (Exception ex)
            {
                SendError(ex);
            }

            return RedirectToAction("List", "App", new { active = true });
        }

        // POST:
        [HttpPost]
        public ActionResult PublishObject(string appID, string objectID)
        {
            try
            {
                BusinessService.PublishObject(objectID);

                SendInformation("Publish Object Successfully!");
            }
            catch (Exception ex)
            {
                SendError(ex);
            }

            return RedirectToAction("List", "Object", new { active = true, appID = appID });
        }

        private void InitDataSource(IEnumerable<MD_Field> fields)
        {

Presentation Layers/Yumiki.Web.Master/Areas/WellCovered/Views/Live/Create.cshtml
@model  Yumiki.Web.WellCovered.Models.MD_LiveRecord

@{
    ViewBag.Title = "Create object";
}

<div class="container">
    <h1>@ViewBag.Title</h1>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        string objectID = Model.ObjectID;

        @Html.Hidden(Yumiki.Web.WellCovered.Controllers.LiveController.ObjectID, objectID)

        <div class="card bg-secondary">
            <div class="card-body p-2">
                <div class="btn-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    @Html.ActionLink("Back", "List", new { objectID = objectID, active = true }, new { @class = "btn btn-dark" })
                </div>
            </div>
        </div>

        foreach (Yumiki.Web.WellCovered.Models.MD_Field field in Model.Fields)
        {
            switch (field.FieldType)
            {
                case Yumiki.Entity.WellCovered.EN_DataType.E_STRING:
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label(field.DisplayName)
                                @if (field.FieldLength > 100)
                                {
                                    @Html.TextArea(field.ApiName, field.Value == null ? string.Empty : field.Value.ToString(), new { @class = "form-control", @rows = 5 })
                                }
                                else
                                {
                                    @Html.TextBox(field.ApiName, field.Value, new { @class = "form-control" })
                                }
                            </div>
                        </div>
                    </div>
                    break;
                case Yumiki.Entity.WellCovered.EN_DataType.E_INT:
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label(field.DisplayName)
                                @Html.TextBox(field.ApiName, field.Value, new { @class = "form-control text-align-right", @type = "number" })
                            </div>
                        </div>
                    </div>
                    break;
                case Yumiki.Entity.WellCovered.EN_DataType.E_DECIMAL:
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label(field.DisplayName)
                                @Html.TextBox(field.ApiName, field.Value, new { @class = "form-control text-align-right", @type = "number", step = "0.01" })
                            </div>
                        </div>
                    </div>
                    break;
                case Yumiki.Entity.WellCovered.EN_DataType.E_BOOL:
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.CheckBox(field.ApiName, field.Value == null ? false : bool.Parse(field.Value.ToString()))
                                @Html.Label(field.ApiName)
                            </div>
                        </div>
                    </div>
                    break;
                case Yumiki.Entity.WellCovered.EN_DataType.E_DATE:
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label(field.DisplayName)
                                <div class="input-group date yumiki-control-date">
                                    @Html.TextBox(field.ApiName, field.Value != null && !string.IsNullOrWhiteSpace(field.Value.ToString()) ? ((DateTime)field.Value).ToString(Yumiki.Commons.Dictionaries.Formats.DateTime.LongDate) : string.Empty, new { @class = "form-control" })
                                    <div class="input-group-append input-group-calendar">
                                        <span class="input-group-text">
                                            <span class="fa fa-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    break;
                case Yumiki.Entity.WellCovered.EN_DataType.E_DATETIME:
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label(field.DisplayName)
                                <div class="input-group date yumiki-control-datetime">
                                    @Html.TextBox(field.ApiName, field.Value != null && !string.IsNullOrWhiteSpace(field.Value.ToString()) ? ((DateTime)field.Value).ToString(Yumiki.Commons.Dictionaries.Formats.DateTime.LongDateTime2) : string.Empty, new { @class = "form-control" })
                                    <div class="input-group-append input-group-calendar">
                                        <span class="input-group-text">
                                            <span class="fa fa-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    break;
                case Yumiki.Entity.WellCovered.EN_DataType.E_TIME:
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label(field.DisplayName)
                                <div class="input-group date yumiki-control-time">
                                    @Html.TextBox(field.ApiName, field.Value != null && !string.IsNullOrWhiteSpace(field.Value.ToString()) ? new DateTime(((TimeSpan)field.Value).Ticks).ToString(Yumiki.Commons.Dictionaries.Formats.DateTime.Hour) : string.Empty, new { @class = "form-control" })
                                    <div class="input-group-append input-group-calendar">
                                        <span class="input-group-text">
                                            <span class="fa fa-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    break;
                case Yumiki.Entity.WellCovered.EN_DataType.E_DATASOURCE:
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.Label(field.DisplayName)
                                @if (((Dictionary<string, SelectList>)ViewBag.Datasources).Any())
                                {
                                    @Html.DropDownList(field.ApiName, ((Dictionary<string, SelectList>)ViewBag.Datasources)[field.ApiName], Yumiki.Commons.Dictionaries.CommonValues.SelectOneForDropDown, new { @class = "form-control selectpicker" })
                                }
                                else
                                {
                                    @Html.DropDownList(field.ApiName, new List<SelectListItem>(), Yumiki.Commons.Dictionaries.CommonValues.SelectOneForDropDown, new { @class = "form-control selectpicker" })
                                }
                            </div>
                        </div>
                    </div>
                    break;
            }
        }
    }
</div>
@section BottomScript{
    @Html.Partial("_WellCoveredInclude")

    <script type="text/javascript">
        yumiki.wellCovered.initDateTimePicker('@Yumiki.Commons.Dictionaries.Formats.DateTime.Hour', '@Yumiki.Commons.Dictionaries.Formats.DateTime.ClientMomentLongDate', '@Yumiki.Commons.Dictionaries.Formats.DateTime.ClientMomentLongDateTime');
    </script>
}

Presentation Layers/Yumiki.Web.Master/Areas/WellCovered/Views/Live/List.cshtml
@using Yumiki.Commons.Dictionaries;

@model Yumiki.Entity.WellCovered.MD_Live

@{
    ViewBag.Title = $"\"{Model.LiveName}\" objects";
}
<div class="container">
    <h1>@ViewBag.Title</h1>
    <div class="card bg-secondary">
        <div class="card-body p-2">
            <div class="btn-group">
                @Html.ActionLink("Add", "Create", new { objectID = Model.ObjectID.ToString() }, new { @class = "btn btn-primary" })

                @{
                    if (string.IsNullOrWhiteSpace(Request.Params[Constants.Active]) || bool.Parse(Request.Params[Constants.Active]))
                    {
                        @Html.ActionLink("Show Inactive", "List", new { active = false, objectID = Model.ObjectID.ToString() }, new { @class = "btn btn-dark" })
                    }
                    else
                    {
                        @Html.ActionLink("Show Active", "List", new { active = true, objectID = Model.ObjectID.ToString() }, new { @class = "btn btn-dark" })
                    }
                }
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-sm table-striped table-bordered table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th></th>
                            <th class="text-right"><i class="fa fa-paperclip"></i></th>
                            @foreach (KeyValuePair<string, Yumiki.Entity.WellCovered.EN_DataType> columnName in Model.ColumnNames)
                            {
                                <th>
                                    @Html.DisplayName(columnName.Key)
                                </th>
                            }
                            
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Datasource != null)
                        {
                            foreach (System.Data.DataRow item in Model.Datasource)
                            {
                                <tr>
                                    <td>
                                        @Html.ActionLink(" ", "Edit", new { objectID = Model.ObjectID.ToString(), recordID = item[Yumiki.Commons.Dictionaries.CommonProperties.ID].ToString() }, new { @class = "fa fa-edit", title = "Edit" })
                                    </td>
                                    @if (item[CommonProperties.Attachments] != null)
                                    {
                                        <td align="right">
                                            @item[CommonProperties.Attachments].ToString()
                                        </td>
                                    }
                                    else
                                    {
                                        <td></td>
                                    }
                                    @foreach (KeyValuePair<string, Yumiki.Entity.WellCovered.EN_DataType> columnName in Model.ColumnNames)
                                    {
                                        object obj = item[columnName.Key];
                                        if (obj != null && !string.IsNullOrWhiteSpace(obj.ToString()))
                                        {
                                            switch (columnName.Value)
                                            {
                                                case Yumiki.Entity.WellCovered.EN_DataType.E_INT:
                                                    <td align="right">
                                                        @((((int)obj).ToString(Yumiki.Commons.Dictionaries.Formats.Number.Integer)))
                                                    </td>
                                                    break;
                                                case Yumiki.Entity.WellCovered.EN_DataType.E_STRING:
                                                case Yumiki.Entity.WellCovered.EN_DataType.E_DATASOURCE:
                                                    <td>
                                                        @obj.ToString()
                                                    </td>
                                                    break;
                                                case Yumiki.Entity.WellCovered.EN_DataType.E_DECIMAL:
                                                    <td align="right">
                                                        @((((decimal)obj).ToString(Yumiki.Commons.Dictionaries.Formats.Number.Decimal)))
                                                    </td>
                                                    break;
                                                case Yumiki.Entity.WellCovered.EN_DataType.E_BOOL:
                                                    <td align="center">
                                                        @Html.CheckBox(columnName.Key, (bool)item[columnName.Key], new { @disabled = "disabled" })
                                                    </td>
                                                    break;
                                                case Yumiki.Entity.WellCovered.EN_DataType.E_DATE:
                                                    <td align="right">
                                                        @(((DateTime)obj).ToString(Yumiki.Commons.Dictionaries.Formats.DateTime.LongDate))
                                                    </td>
                                                    break;
                                                case Yumiki.Entity.WellCovered.EN_DataType.E_DATETIME:
                                                    <td align="right">
                                                        @(((DateTime)obj).ToString(Yumiki.Commons.Dictionaries.Formats.DateTime.LongDateTime2))
                                                    </td>
                                                    break;
                                                case Yumiki.Entity.WellCovered.EN_DataType.E_TIME:
                                                    <td align="right">
                                                        @(new DateTime(((TimeSpan)obj).Ticks).ToString(Yumiki.Commons.Dictionaries.Formats.DateTime.Hour))
                                                    </td>
                                                    break;
                                            }
                                        }
                                        else
                                        {
                                            <td></td>
                                        }
                                    }
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Presentation Layers/Yumiki.Web.Master/Areas/WellCovered/Views/Live/Search.cshtml
@model Yumiki.Entity.MoneyTrace.ServiceObjects.GetSearchIndexResponse

@{
    ViewBag.Title = "Search";
}
<style type="text/css">
    mark {
        background-color: #ffc107;
        border-radius: 5px;
        padding:.1em;
    }
</style>
<div class="container">
    <h1>@ViewBag.Title</h1>
    <div class="row">
        <div class="col-md-6">
            @using (Html.BeginForm("Search", "Live", FormMethod.Get, new { id = "frmLiveSearch" }))
            {
                <div class="input-group">
                    @Html.TextBox("keywords", null, new { placeholder = "Search for...", @class = "form-control", id = "txtSearchBox" })
                    <div class="input-group-append">
                        <button type="button" class="btn btn-primary" id="btnSearch"><span class="fa fa-search"></span></button>
                    </div>
                </div>
            }
        </div>
    </div>
    @if (Model != null && Model.Records != null)
    {
        <hr />
        <div class="row">
            @foreach (var item in Model.Records)
            {
                <div class="col-md-8">
                    <div class="yumiki-search-item">
                        @Html.Raw(item.DisplayContents)
                    </div>
                    <div>
                        @Html.ActionLink("Go to Object List...", "List", "Live", new { objectID = item.ObjectID, active = true }, new { target = "_blank" })
                        @Html.ActionLink("View details...", "Edit", "Live", new { objectID = item.ObjectID, recordID = item.LiveID }, new { target = "_blank" })
                    </div>
                    <hr />
                </div>
            }
        </div>
        if (Model.TotalItems == 0)
        {
            <i>
                @Html.Raw("No results found.")
            </i>
        }

        //Paging
        else if(Model.StartPage != Model.EndPage)
        {
            <ul class="pagination">
                @if (Model.StartPage > 1)
                {
                    <li class="page-item">
                        @Html.ActionLink(" ", "Search", "Live", new { keywords = Request.QueryString["keywords"], pageIndex = 1 }, new { @class = "page-link fa fa-step-backward" })
                    </li>
                }
                @for (int i = Model.StartPage; i <= Model.EndPage; i++)
                {
                    <li class="page-item @(i == Model.CurrentPage ? "active" : string.Empty)">
                        @Html.ActionLink(i.ToString(), "Search", "Live", new { keywords = Request.QueryString["keywords"], pageIndex = i }, new { @class= "page-link" })
                    </li>
                }
                @if (Model.EndPage != Model.TotalPages)
                {
                    <li class="page-item">
                        @Html.ActionLink(" ", "Search", "Live", new { keywords = Request.QueryString["keywords"], pageIndex = Model.TotalPages }, new { @class = "page-link fa fa-step-backward" })
                    </li>
                }
            </ul>
        }
    }
</div>
@section BottomScript{
    @Html.Partial("_WellCoveredInclude")

    <script type="text/javascript">
        $(document).ready(function () {
            yumiki.wellCovered.initSearchEvent('txtSearchBox', 'btnSearch', 'frmLiveSearch');
        });
    </script>
}